dist: focal
language: cpp
sudo: required

matrix:
  include:
    - name: gcc on linux
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
      env:
        - MATRIX_EVAL="CMAKE_GENERATOR='Unix Makefiles' && CXX=g++-10"
    - name: clang on linux
      os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-10
      env:
        - MATRIX_EVAL="CMAKE_GENERATOR='Unix Makefiles' && CXX=clang++-10"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir -p build && cd $_
  - cmake -G "$CMAKE_GENERATOR" ..

script:
  - cmake --build . -j

